export { api, apiJson, handleApiError, type APIError } from "./api"
export { authService } from "./auth"
export { contactsService } from "./contacts"
export { tagsService } from "./tags"
export { creditsService } from "./credits"
export { dashboardService } from "./dashboard"
export { organizationsService } from "./organizations"
export { invitationsService } from "./invitations"
export { creditRequestsService } from "./credit-requests"
export { adminApi, setAdminToken, clearAdminToken } from "./admin-api"
export { adminService } from "./admin"
export { customFieldsService } from "./custom-fields"
export { whatsappService } from "./whatsapp"
export { scenariosService } from "./scenarios"
export { conversationsService } from "./conversations"
export { aiToolsService } from "./ai-tools"
export { aiCreditsService } from "./ai-credits"
export { agentsService } from "./agents"
export { pdfTemplatesService } from "./pdf-templates"
export { segmentsService } from "./segments"
export type { Segment, SegmentCriteria, SegmentRule, RuleGroup, GroupOperator, RuleOperator, SegmentContact, PreviewResult } from "./segments"
export { automationsService } from "./automations"
export type { Automation, AutomationStep, AutomationEnrollment, TriggerType, StepType, EnrollmentStatus } from "./automations"
